typography_spectrum: 0.7520807639230043
color:
  saturation: 0.3278823508881032
  brandStrength: 1
  lightness: 0.1487238612025976
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#C3B7AF'
    - '#44403F'
    - '#B0651F'
  rhythmicContrast: 0.7328044306486845
layout_spectrum: 0.843985
author:
  email: spiros@anotherkindart.gr
  url: 'http://www.anotherkindart.gr/'
  name: Spiros Doukeris
name: AnotherKindArt
navigation:
  - name: About
    id: c5480780-951d-4bd9-a3c3-61558432936b
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Ειδικές Κατασκευές - Θεατρικά Σκηνικά
description: Κατασκευή Σκηνικών Θεάτρου & Aνακαινίσεις Επαγγελματικών Χώρων
